const data = {
  jewellery_type: [
    "Choose Item",
    "Plain Gold Jewellery",
    "Plain Gold Jewellery with Stones",
  ],
  product_type: [
    "Choose Item",
    "Anklet",
    "Bangle",
    "Bracelet",
    "Chain",
    "Earrings",
    "Finger Rings",
    "Gold Coin",
    "Haram",
    "Jewellery Set",
    "Kada",
    "Maang Teeka",
    "Mangalsutra",
    "Mangalsutra Set",
    "Neckwear",
    "Nose Pin",
    "Pendant",
    "Pendant and Earrings Set",
    "Pendant with Chain",
    "Pendant With chain and Earring Set",
    "Silver Coin",
    "Waist Belt",
  ],
  Gender: ["Choose Item", "Women", "Men", "Kids", "Unisex"],
  Metal_color: [
    "Choose Item",
    "Rose",
    "Rose and White",
    "White",
    "White and Rose",
    "Yellow",
    "Yellow and Rose",
    "Yellow and White",
  ],
  purity: ["Choose Item", 0.0, 14.0, 18.0, 22.0, 24.0],
  bangles_size: [
    "Choose Item",
    "38 mm",
    "42 mm",
    "45 x 55 mm",
    "47 x 57 mm",
    "52.50 mm",
    "53 x 60 mm",
  ],
  bracelet_size: [
    "Choose Item",
    "12 cm",
    "14 cm",
    "16 cm",
    "16.50 cm",
    "17.50 cm",
    "18 cm",
  ],
  chain_size: [
    "Choose Item",
    "33.02 cm",
    "35.56 cm",
    "38.1 cm",
    "40.64 cm",
    "43.18 cm",
    "45.72 cm",
  ],
  ring_size: [
    "Choose Item",
    "12 mm",
    "12.40 mm",
    "12.80 mm",
    "13.20 mm",
    "13.60 mm",
    "14.40 mm",
  ],
  metal: ["Choose Item", "Gold", "Silver", "Platinum"],
  community_type: [
    "Choose Item",
    "Bengali",
    "Bihari",
    "Contemporary",
    "Gujrati",
    "Indian Bridal",
    "Kannada",
  ],
  coin_weight: [
    "Choose Item",
    "1 gram",
    "10 grams",
    "100 grams",
    "1000 grams",
    "2 grams",
    "25 grams",
  ],
  mangalsutra_size: [
    "Choose Item",
    "30.48 cm",
    "40.64 cm",
    "45.72 cm",
    "50.8 cm",
    "53.34 cm",
    "60.96 cm",
  ],
  pendant_height: [
    "Choose Item",
    "11 mm",
    "18 mm",
    "20 mm",
    "22 mm",
    "23 mm",
    "25 mm",
  ],
  pendant_width: [
    "Choose Item",
    "10 mm",
    "12 mm",
    "13 mm",
    "15 mm",
    "16 mm",
    "17 mm",
  ],
  earring_height: ["Choose Item", "10 mm", "11 mm", "12 mm", "13 mm", "14 mm"],
  earring_width: ["Choose Item", "10 mm", "11 mm", "12 mm", "13 mm", "14 mm"],
  units: ["Gram", "Ounce", "Kilo", "Tola", "Masha", "Ratti"],
};

export default data;
